### ISSUE TITLE
Path::Class only used for basename?

### ISSUE THREAD

**Issue by shadowcat-mst** [hirose31/IO-File-AtomicChange#2]
Is there any reason this can't be replaced with the core File::Basename?

**Comment by hirose31** [comment]
There is no particular reason. I will merge the PR using File::Basename.

**Comment by ap** [comment]
@shadowcat-mst: Path::Class is not used not only for basename, it also has some minor use in the tests. Using File::Basename alone won’t get rid of it.

I offered #3 to remove the use of Path::Class but @hirose31 decided he wants to keep it.
