### ISSUE TITLE
Is File::Sync necessary?

### ISSUE THREAD

**Issue by ap** [hirose31/IO-File-AtomicChange#4]
IO::File::AtomicChange loads File::Sync to call `fsync`.

But it already inherits from IO::File which inherits from IO::Handle which has always had a `sync` method that calls `fsync`. Calling that would avoid a dependency.

Is just calling `$self->sync` problematic for some reason I’m not aware of? The File::Sync documentation does not describe any differences between its `fsync` function and the IO::Handle `sync` method, so the answer would seem to be no, but I’m not sure.

(As far as I can tell, the only reason anyone might ever need File::Sync is that it also provides an `fdatasync` function. But IO::File::AtomicChange doesn’t use that.)

**Comment by hirose31** [comment]
Thanks!
